title: People's Association
url: https://www.pa.gov.sg
favicon: /images/Fav-Icon.ico
colors:
  primary-color: "#e21822"
  secondary-color: "#e21822"
  media-colors:
    - title: media-color-one
      color: "#b7b7b7"
    - title: media-color-two
      color: "#474747"
    - title: media-color-three
      color: "#474747"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
resources_name: news-and-speeches
description: An Isomer site of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.dcnlqhfit47h.amplifyapp.com/
prod: https://master.dcnlqhfit47h.amplifyapp.com/
shareicon: /images/isomer-logo.svg
is_government: true
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
